### ISSUE TITLE
Upgrade to connect-mongodb@3

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-session-mongodb#7]
There's a potential security vulnerability in a sub-dependency: https://github.com/digitalbazaar/bedrock-session-mongodb/pull/6

The simple solution is to upgrade to connect-mongodb@3.  Need to assess breaking changes.

https://github.com/senchalabs/connect/blob/master/HISTORY.md#300-rc1--2014-03-06

**Comment by davidlehn** [comment]
connect?  Did you mean connect-mongo@3?  That uses mongodb@3, but bedrock-mongodb is still using 2.  That is a thing we should upgrade, but may be more involved?

**Comment by mattcollier** [comment]
@davidlehn you are correct, I updated the description to be `connect-mongodb`.  And you've also already identified the first possible sticking point.  It seems like it *might* be OK for this module to use whatever version mongodb driver it likes.

**Comment by dlongley** [comment]
If we want to replace the dependency with something better/more modern that's also acceptable. I'm not sure how much external API surface there is here -- it may just be an express session store that can be completely swapped out. The thing we're currently using has us doing some weird async tricks to make it work properly and it would be nice to eliminate that.

**Comment by mandyvenables** [comment]
Fixed with PR #8
